added course pages and link to follow up course
lablueprint/end-overdose pull request #2
Opened 2024-11-22 06:20 UTC by KianBaghai

## Description
Made a new courses page and added a link to the first course

2024-11-22 07:01 UTC, joycechen721 requested changes

2024-11-28 18:40 UTC, coshio commented on src/app/courses/opiod/page.tsx
> +import React from 'react';
this was resolved in following commits :)

2024-12-02 21:29 UTC, WCheyenneLu commented
# Courses-1 (Kian, Cheyenne)
## Description:
- On main home page for courses, each course is displayed using the Course component
- Each course has two modules (for now) which has multiple pages (dynamic routing)
- Pages have two buttons that help navigate to previous page and next page (useParams, url coerced into number to add and subtract 1) 
- timer created for a simple page so that users have to have the page open for at least 10 seconds before moving on to the next
## Components:
### Course.tsx
  **Functionality**: 
- takes in coursePath, courseProgress, courseTitle props from the course home page, onClick navigates to the respective course's page
- displays progress as progress bar with <progess> tag
### Module.tsx
  **Functionality**: 
- takes in coursePath, courseProgress, courseTitle props from the course (career or opioid) page, onClick navigates to the first page of the course
- displays progress as progress bar with <progess> tag
### SimplePage.tsx
  **Functionality**: The basic structure of a 'standard' page, requires user to stay on that page for at least 10 seconds before they are able to move one (functional timer state that stops at 10 but further implementations will be executed in the future)
### VideoPage.tsx
  **Functionality**: The basic structure of a page in the module that may have video content
## To Do:
- Add percentage to progress bar
- Add props to simple page so correct information displayed, use the timer state for rendering next page options

2024-12-02 21:30 UTC, cheyennelu17 commented
# Courses-1 (Kian, Cheyenne)
## Description:
- On main home page for courses, each course is displayed using the Course component
- Each course has two modules (for now) which has multiple pages (dynamic routing)
- Pages have two buttons that help navigate to previous page and next page (useParams, url coerced into number to add and subtract 1) 
- timer created for a simple page so that users have to have the page open for at least 10 seconds before moving on to the next
## Components:
### Course.tsx
  **Functionality**: 
- takes in coursePath, courseProgress, courseTitle props from the course home page, onClick navigates to the respective course's page
- displays progress as progress bar with <progess> tag
### Module.tsx
  **Functionality**: 
- takes in coursePath, courseProgress, courseTitle props from the course (career or opioid) page, onClick navigates to the first page of the course
- displays progress as progress bar with <progess> tag
### SimplePage.tsx
  **Functionality**: The basic structure of a 'standard' page, requires user to stay on that page for at least 10 seconds before they are able to move one (functional timer state that stops at 10 but further implementations will be executed in the future)
### VideoPage.tsx
  **Functionality**: The basic structure of a page in the module that may have video content
## To Do:
- Add percentage to progress bar
- Add props to simple page so correct information displayed, use the timer state for rendering next page options

2024-12-03 03:57 UTC, coshio approved these changes
Great work you guys and really good PR documentation

2024-12-03 03:57 UTC, coshio approved these changes

2024-12-03 06:00 UTC, joycechen721 approved these changes
looks gassss THANKS GUYS

2024-12-03 06:01 UTC, merged